CREATE TABLE [dbo].[UserRole]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] INT NOT NULL, 
    [RoleId] INT NOT NULL,
    CONSTRAINT [FK_UserRole_ToUser] FOREIGN KEY (UserId) REFERENCES [User](Id),
    CONSTRAINT [FK_UserRole_ToRole] FOREIGN KEY (RoleId) REFERENCES [Role](Id)
)
