CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserName] NVARCHAR(50) NOT NULL, 
    [Password] NVARCHAR(100) NOT NULL, 
    [PasswordSalt] NVARCHAR(50) NOT NULL, 
    [Prefix] NVARCHAR(50) NULL, 
    [LastName] NVARCHAR(100) NOT NULL, 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [MiddleName] NVARCHAR(50) NULL, 
    [Suffix] NVARCHAR(50) NULL, 
    [Gender] NVARCHAR(10) NULL, 
    [Email] NVARCHAR(255) NOT NULL, 
    [Position] NVARCHAR(255) NOT NULL, 
    [ProfilePicture] NVARCHAR(255) NULL, 
    [Signature] NVARCHAR(255) NULL, 
    [IsOnline] BIT NOT NULL DEFAULT 0, 
    [LastOnlineTime] DATETIME2 NULL , 
    [IsDisabled] BIT NOT NULL DEFAULT 0, 
    [LockedTime] DATETIME2 NULL, 
    [LastFailedAttempt] DATETIME2 NULL, 
    [FailedAttempts] INT NULL, 
    [RefreshToken] NVARCHAR(255) NULL, 
    [RefreshTokenExpiryTime] DATETIME2 NULL,
    [CreatedById] INT NOT NULL, 
    [DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [ModifiedById] INT NULL, 
    [DateModified] DATETIME2 NULL 
);
