// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class AuditTrail
{
    public int Id { get; set; }

    public string Action { get; set; }

    public string TableName { get; set; }

    public string RecordPk { get; set; }

    public string ColumnName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public DateTime ChangeDate { get; set; }

    public int UserId { get; set; }
}