// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class CompanySetting
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int? Bir2307Basis { get; set; }

    public int? PostingPeriod { get; set; }

    public string AccountingPeriod { get; set; }

    public string AcctgPeriodFrom { get; set; }

    public string AcctgPeriodTo { get; set; }

    public int InvEvalMethodId { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? TransactionSeriesCount { get; set; }

    public bool? IsBypassApApproval { get; set; }

    public int? CwtId { get; set; }

    public virtual Company Company { get; set; }
}