// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class Company
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string BusinessStyle { get; set; }

    public string TelNo { get; set; }

    public string MobileNo { get; set; }

    public string FaxNo { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string Tin { get; set; }

    public string RepresentativeName { get; set; }

    public string RepresentativeTin { get; set; }

    public string RepresentativeDesignation { get; set; }

    public bool IsDisabled { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }

    public virtual ICollection<CompanyLogo> CompanyLogos { get; set; } = new List<CompanyLogo>();

    public virtual ICollection<CompanySetting> CompanySettings { get; set; } = new List<CompanySetting>();
}