// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class Currency
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int CountryId { get; set; }

    public string Symbol { get; set; }

    public bool IsDefault { get; set; }

    public int CompanyId { get; set; }

    public bool IsDisabled { get; set; }

    public decimal Rate { get; set; }

    public bool Inactive { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }
}