// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class Module
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public int ModuleTypeId { get; set; }

    public int Ordinal { get; set; }

    public string Icon { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public int? ParentModuleId { get; set; }

    public int ApprovalRouteTypeId { get; set; }

    public bool IsDisabled { get; set; }

    public bool InMaintenance { get; set; }

    public bool? IsVisible { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }

    public virtual ModuleType ModuleType { get; set; }

    public virtual ICollection<RoleAccess> RoleAccesses { get; set; } = new List<RoleAccess>();
}