// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class ModuleSetting
{
    public int Id { get; set; }

    public int ModuleId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string DefaultValue { get; set; }

    public string Value { get; set; }

    public string DateType { get; set; }

    public string Selection { get; set; }

    public int CompanyId { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }
}