// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class User
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string PasswordSalt { get; set; }

    public string Prefix { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Suffix { get; set; }

    public string Gender { get; set; }

    public string Email { get; set; }

    public string Position { get; set; }

    public string ProfilePicture { get; set; }

    public string Signature { get; set; }

    public bool IsOnline { get; set; }

    public DateTime? LastOnlineTime { get; set; }

    public bool IsDisabled { get; set; }

    public DateTime? LockedTime { get; set; }

    public DateTime? LastFailedAttempt { get; set; }

    public int? FailedAttempts { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }

    public virtual ICollection<UserActivity> UserActivities { get; set; } = new List<UserActivity>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}