// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class Vendor
{
    public int Id { get; set; }

    public string VendorCode { get; set; }

    public string VendorName { get; set; }

    public int EwtTypeId { get; set; }

    public int VatTypeId { get; set; }

    public int CompanyId { get; set; }

    public string ProfilePicture { get; set; }

    public string TinNo { get; set; }

    public int? TaxPayerType { get; set; }

    public int? PaymentTermId { get; set; }

    public string EmailAddress { get; set; }

    public string MobileNo { get; set; }

    public string TelNo { get; set; }

    public string FaxNo { get; set; }

    public string Website { get; set; }

    public bool IsDisabled { get; set; }

    public bool Inactive { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }
}